### ISSUE TITLE
npm run dev 

### ISSUE THREAD

**Issue by YangTao0** [dnsjia/luban#21]
98% after emitting CopyPlugin
ERROR  Failed to compile with 1 error                                                                                                             5:00:05 PM

This dependency was not found:

* _vue-router@4.0.12@vue-router in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--0-1!./src/views/cmdb/Index.vue?vue&type=script&lang=js

To install it, you can run: npm install --save _vue-router@4.0.12@vue-router
#
 npm install --save _vue-router@4.0.12@vue-router
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "_vue-router": name cannot start with an underscore

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-29T09_01_17_535Z-debug.log

**Comment by YangTao0** [comment]
^C[root@sysmonitor02-prod-ucscompute22rgb-vianetm5 luban_fe]# npm install --save _vue-router@4.0.12@vue-router
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "_vue-router": name cannot start with an underscore

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-29T09_01_17_535Z-debug.log

**Comment by zijiwork** [comment]
该问题已被修复，请重新Pull master分支，再执行npm install
