### ISSUE TITLE
打包前端 vue 部署在Nginx上无法跳转

### ISSUE THREAD

**Issue by YangTao0** [dnsjia/luban#22]
你好，咨询一下，如何把vue前端部署在Nginx上，我得配置如下，访问ip:8080 之后点击登录，后端go的8002和Nginx日志没有接收到请求：
server {
  listen 8080;
  server_name  localhost;

  location / {
      index index.html index.htm;
      root /root/go/src/luban/luban_fe/dist/;
     }

  location ~ ^/api/ {
      proxy_set_header   Host             $http_host;
      proxy_set_header   X-Real-IP        $remote_addr;
      proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto  $scheme;
      #rewrite ^/api/(.*)$ /$1 break;
      proxy_pass  http://localhost:8002;
      }
}

**Comment by eagle9527** [comment]
```
         location / {
             root /usr/share/nginx/html;
             add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
             try_files $uri $uri/ /index.html;
         }
```
参考一下这个试试

**Comment by eagle9527** [comment]
location /api {
             proxy_set_header Host $http_host;
             proxy_set_header  X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header X-Forwarded-Proto $scheme;
             rewrite ^/api/(.*)$ /$1 break;  #重写
             proxy_pass http://dolphin:8888; # 设置代理服务器的协议和地址
          }
