### ISSUE TITLE
这里不太合理, 其他k8s集群会报错

### ISSUE THREAD

**Issue by ysicing** [dnsjia/luban#23]
https://github.com/dnsjia/luban/blob/7e0ef94aba9b8b21a3a845eb8b0ed5385230909d/pkg/k8s/cluster/cluster.go#L102

**Comment by gujiwork** [comment]
需要在每个集群中安装kube-state-metrics， 请参考https://github.com/dnsjia/luban/wiki/%E9%83%A8%E7%BD%B2-kube-state-metrics
