### ISSUE TITLE
你好，目前发布功能，和用户管理是还没有开发还是目前我操作有误？

### ISSUE THREAD

**Issue by ShaoZeMing** [dnsjia/luban#24]
## 问题描述
类型：功能请求

发布管理
用户管理

## 描述你想要什么功能

能基于容器仓库，对指定版本容器镜像发布到指定项目中，发布状态，回滚状态。

## 附加上下文
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by zijiwork** [comment]
应用发布这块后期会开发， 目前在完善其他功能

**Comment by ShaoZeMing** [comment]
> 应用发布这块后期会开发， 目前在完善其他功能

期待，大佬辛苦了

**Comment by zijiwork** [comment]
已支持应用发布功能，具体参考文档升级
https://docs.dnsjia.com/upgrade/changelog/
