### ISSUE TITLE
最新代码启动登陆报错

### ISSUE THREAD

**Issue by reckless-huang** [dnsjia/luban#28]
errMsg: "sql: Scan error on column index 1, name \"created_at\": can not convert [50 48 50 49 45 48 57 45 49 56 32 49 50 58 51 48 58 50 56] to LocalTime"

**Comment by reckless-huang** [comment]
刷的sql下的init.sql

**Comment by reckless-huang** [comment]
以解决

**Comment by KropWu** [comment]
大佬能分享下解决方法吗
