### ISSUE TITLE
请问源码运行前后端，前端无法请求到后端如何排查

### ISSUE THREAD

**Issue by printWSL** [dnsjia/luban#30]
前后端正常运行
![image](https://user-images.githubusercontent.com/45867248/180333495-f0ed256d-dc3e-4d5c-8933-5e1146fdc8d2.png)
![image](https://user-images.githubusercontent.com/45867248/180333508-d8a714e6-c7c2-40f2-b99a-d08ad7b24406.png)
通过前端登录无响应，后端也没有接口访问日志
![image](https://user-images.githubusercontent.com/45867248/180334417-77ac9952-a30c-4efc-9ff7-9edb9a0fe4a7.png)

![image](https://user-images.githubusercontent.com/45867248/180333620-ec81bd9a-766e-40b5-a863-b79da43ed4e8.png)
通过curl访问前端返回的后端接口地址可以正常到达后端
![image](https://user-images.githubusercontent.com/45867248/180334292-33f6c29e-d905-43e3-9be0-99a0842b670e.png)
![image](https://user-images.githubusercontent.com/45867248/180334308-540058d5-dd72-43e7-89cf-289346b8e342.png)

请帮忙确认是不是启动方式有问题，非常感谢

**Comment by gujiwork** [comment]
前端配置文件中连接api地址配置是同一个ip吗？ 浏览器访问ip和后端ip保持一致即可

**Comment by cwp2088** [comment]
我也碰到同样问题 访问前端 后端无响应
