### ISSUE TITLE
使用Docker运行程序后，连接的外部的MYSQL数据库，并导入的master下的sql/luban_init.sql后，使用luban/test1234登陆后没有任何菜单，请问在哪里初始化菜单、角色、关系表。

### ISSUE THREAD

**Issue by chinapsu** [dnsjia/luban#34]
![image](https://user-images.githubusercontent.com/6300044/189877081-9f1080b1-5e0b-4c01-a04b-07c2f2da4d6a.png)

![image](https://user-images.githubusercontent.com/6300044/189877258-6ee5e4c6-6810-42ce-931e-260c2bbd7bd5.png)

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '''自增编号''',
  `created_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `username` VARCHAR(128) DEFAULT NULL COMMENT '''用户名''',
  `password` VARCHAR(128) DEFAULT NULL COMMENT '''用户密码''',
  `phone` VARCHAR(11) DEFAULT NULL COMMENT '''手机号码''',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '''邮箱''',
  `nick_name` VARCHAR(128) DEFAULT NULL COMMENT '''用户昵称''',
  `avatar` VARCHAR(128) DEFAULT 'http://dnsjia.com/img/avatar.png' COMMENT '''用户头像''',
  `status` TINYINT(1) DEFAULT '1' COMMENT '''用户状态(正常/禁用, 默认正常)''',
  `role_id` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '''角色id外键''',
  `dept_id` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '''部门id外键''',
  `uid` BIGINT(20) DEFAULT NULL COMMENT '''用戶uid''',
  `create_by` VARCHAR(191) DEFAULT NULL COMMENT '''创建来源''',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`),
  KEY `idx_users_deleted_at` (`deleted_at`)
) ENGINE=INNODB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('1', '2021-09-18 12:30:28', '2021-09-18 12:30:28', NULL, 'luban', '$2a$10$zn0dAfLmdIC2ff9dkAN7LezbwUFaHfsR6Aqis/jLHTJFy5rBUeey6', '0', 'luban@qq.com', '', 'http://dnsjia.com/img/avatar.png', '1', '1', '0', NULL, NULL);

**Comment by gujiwork** [comment]
使用Docker方式启动，mysql也需要使用封装过的容器启动，请参考： https://docs.dnsjia.com/getting-started/installation/
