### ISSUE TITLE
按照文档使用docker方式安装不成功

### ISSUE THREAD

**Issue by liuts** [dnsjia/luban#54]
docker run -itd --name luban -p 8080:8080 -v /root/luban/etc:/data/luban/etc dnsjia/luban:latest

这里的挂载到docker里面目录是不是有问题，推测应该是/apps//luban/etc
-v /root/luban/etc:/data/luban/etc

**Comment by ljy-life** [comment]
文档有问题，而且docker里边也没有前端的相关启动程序
