### ISSUE TITLE
demo 登陆一直账号密码错误

### ISSUE THREAD

**Issue by hellogy** [dnsjia/luban#57]
## 问题描述
类型：功能请求
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/22974663/215254470-92edbc68-4df5-4801-a4fa-1c76df7bfbdb.png">

## 附加上下文
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by zjluoyue** [comment]
账号密码一直是错的，看不了demo
