### ISSUE TITLE
目前登陆demo 环境提示用户被禁用

### ISSUE THREAD

**Issue by redgra0315** [dnsjia/luban#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/48678307/221340208-c081fade-b322-4c94-b53e-8f141567fb19.png">

**Comment by zijiwork** [comment]
请使用docker-compose部署，https://docs.dnsjia.com/upgrade/changelog/
