### ISSUE TITLE
初始化失败了

### ISSUE THREAD

**Issue by qiaocco** [dnsjia/luban#64]
初始化的时候，这个表被注释掉了
<img width="945" alt="image" src="https://user-images.githubusercontent.com/25075484/227761611-a4c48b17-1ae9-42c3-90aa-540495fbd283.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/25075484/227761630-88586199-5d9e-44d7-b0af-f8f1f527570e.png">

**Comment by zijiwork** [comment]
[使用docker-compose启动](https://github.com/dnsjia/luban/wiki/%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85#%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85)
