### ISSUE TITLE
master分支默认账号密码是啥呢luban@qq.com

### ISSUE THREAD

**Issue by WeberMu** [dnsjia/luban#65]
![image](https://user-images.githubusercontent.com/32811427/234166526-fe288e1c-1c8a-40c8-879c-a9f18d4b87cd.png)

**Comment by ShyunnY** [comment]
解决了吗？我用README的默认账号密码都无法登录。

**Comment by WeberMu** [comment]
数据库用户表手动新增一条记录，根据创建用户接口生成密码
