### ISSUE TITLE
跟随文档搭建项目，初始化项目时候，数据库没有数据。

### ISSUE THREAD

**Issue by ShyunnY** [dnsjia/luban#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zijiwork** [comment]
https://docs.dnsjia.com/upgrade/changelog/ 导入[v2.2.0.sql](https://docs.dnsjia.com/upgrade/sql/v2.2.0.sql)

**Comment by lakevilladom** [comment]
admin/luban123  提示密码错误
